displayName=Log Hunter Suggestions
project.version=1.0.0
author=carve084
description=Suggests time-efficient activities for Collection Log slots and Skill Levels based on your current stats.
tags=collection log, efficiency, pvm, skilling, suggestions
repository=https://github.com/carve084/Log-Hunter-Suggestions
commit=898bd156be156b2ce375b83f06e485c7346a5f74
plugins=com.carve084.loghunter.LogHunterPlugin